<Project Sdk="Dalamud.NET.Sdk/15.0.0">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <AssemblyName>ARankHuntTourAssistant</AssemblyName>
    <RootNamespace>ARankHuntTourAssistant</RootNamespace>
    <Version>0.1.0</Version>
  </PropertyGroup>
  <ItemGroup>
    <None Include="ARankHuntTourAssistant.json" CopyToOutputDirectory="PreserveNewest" />
    <None Include="images\icon.png" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
